name: csc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with csc
      working-directory: .
      run: csc /out:cschelper.exe *.cs
    - name: Upload
    - uses: actions/upload-artifact@v3
      with:
        name: cschelper
        path: cschelper.exe
